# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- main

pool:
  name: 'Azure Pipelines'


steps:
- task: UseJavaVersion@1
  inputs:
    version: '11'
    architecture: 'x64'
- script: |
    echo "Running pipeline!"
    java -version
  displayName: 'Run a script'



  
