# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default

steps:
- task: UseJavaVersion@1
  inputs:
    versionSpec: '11'
    jdkArchitecture: 'x64'

- script: |
    echo "Building the project"
    mvn clean install
  displayName: 'Build the project'

- script: |
    echo "Running tests"
    mvn test
  displayName: 'Run tests'
- script: |
    echo "Building the project"
    mvn clean install
  displayName: 'Build the project'

- script: |
    echo "Running tests"
    mvn test
  displayName: 'Run tests'

  
