trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseNode@2
  inputs:
    version: '16.x'
- script: npm install
  displayName: 'Install Dependencies'
- script: npm test
  displayName: 'Run Tests'
- script: npm run build
  displayName: 'Build Project'
