# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- main

pool:
  name: Default  # or 'vmImage: ubuntu-latest' if using a hosted agent

steps:
- script: |
    echo "Setting up Java 11"
    sudo apt update
    sudo apt install -y openjdk-11-jdk
    java -version
  displayName: 'Set up Java'

- script: |
    echo "Building the project"
    mvn clean install
  displayName: 'Build the project'

- script: |
    echo "Running tests"
    mvn test
  displayName: 'Run tests'




  
